koxudaxi/datamodel-code-generator

.travis.yml

The PR fix conditions when deploy 
https://github.com/koxudaxi/datamodel-code-generator/issues/5#issuecomment-514191245

add conditions for deployment

---

.coveragerc
.travis.yml
datamodel_code_generator/model/base.py
datamodel_code_generator/parser/openapi.py
tests/model/test_base.py
tests/test_dummy.py

add unittest
https://github.com/koxudaxi/datamodel-code-generator/issues/15

add unittest

---

.travis.yml
datamodel_code_generator/parser/base.py
datamodel_code_generator/parser/openapi.py
setup.cfg
tests/parser/test_openapi.py

https://github.com/koxudaxi/datamodel-code-generator/issues/30

add supported formats

---

datamodel_code_generator/parser/base.py
datamodel_code_generator/parser/openapi.py
tests/data/duplicate_models.yaml
tests/parser/test_openapi.py

The PR fixes to create duplicate models.

 Support duplicate models

---

MANIFEST.in
datamodel_code_generator/model/enum.py
datamodel_code_generator/model/template/Enum.jinja2
datamodel_code_generator/parser/base.py
datamodel_code_generator/parser/openapi.py
tests/data/enum_models.yaml
tests/parser/test_openapi.py

https://github.com/koxudaxi/datamodel-code-generator/issues/27

support enum

---

datamodel_code_generator/parser/openapi.py
tests/data/anyof.yaml
tests/parser/test_openapi.py

The PR supports  `anyof` as `Union` .

support anyof

---

datamodel_code_generator/model/base.py
datamodel_code_generator/model/pydantic/base_model.py
datamodel_code_generator/model/pydantic/custom_root_type.py
datamodel_code_generator/model/pydantic/dataclass.py
datamodel_code_generator/model/template/pydantic/BaseModel.jinja2
datamodel_code_generator/model/template/pydantic/BaseModel_root.jinja2
datamodel_code_generator/model/template/pydantic/dataclass.jinja2
datamodel_code_generator/parser/base.py
datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/parser/openapi.py
tests/data/allof.yaml
tests/model/pydantic/test_base_model.py
tests/model/pydantic/test_custom_root_type.py
tests/model/pydantic/test_data_class.py
tests/model/test_base.py
tests/parser/test_base.py
tests/parser/test_openapi.py

The PR supports `allOf` of openapi

Support allOf

---

.travis.yml
scripts/format.sh
scripts/lint.sh
scripts/test.sh

The PR adds scripts for  test, lint, and format
We should run the format script before to push to Github.

add scripts for test, lint, and format

---

datamodel_code_generator/model/pydantic/types.py
datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/types.py
tests/data/modular.yaml
tests/parser/test_openapi.py
tests/test_main.py

adds support for object as list element

add support for object arrays

---

datamodel_code_generator/parser/jsonschema.py
setup.cfg

update dependency versions

---

datamodel_code_generator/__main__.py
datamodel_code_generator/model/base.py
datamodel_code_generator/model/pydantic/base_model.py
datamodel_code_generator/model/pydantic/custom_root_type.py
datamodel_code_generator/model/pydantic/dataclass.py
datamodel_code_generator/model/template/pydantic/BaseModel.jinja2
datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/parser/openapi.py
tests/data/additional_properties.yaml
tests/parser/test_openapi.py

The PR supports `bool` on `additionalProperties`.
https://github.com/koxudaxi/datamodel-code-generator/issues/82

Support bool on additionalProperties

---

README.md
datamodel_code_generator/parser/base.py
datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/parser/openapi.py
scripts/test.sh
tests/data/external_child.json
tests/data/external_child.yaml
tests/data/external_parent.json
tests/parser/test_base.py
tests/parser/test_jsonschema.py
tests/parser/test_openapi.py

This PR supports remote reference.

Support remote reference

---

README.md
datamodel_code_generator/model/pydantic/types.py
tests/parser/test_openapi.py
tests/test_main.py
tests/test_main_kr.py

This PR change url validator from `UrlStr` to `AnyUrl`

change url validator

---

datamodel_code_generator/__main__.py
datamodel_code_generator/parser/jsonschema.py
tests/parser/test_jsonschema.py

This PR supports empty object as any root object
https://github.com/koxudaxi/datamodel-code-generator/issues/102

support empty object as any root object

---

datamodel_code_generator/model/base.py
tests/model/pydantic/test_base_model.py

This PR supports reserved words as a field (None, def, yield, False ...)
https://github.com/koxudaxi/datamodel-code-generator/issues/102

support reserved words as field

---

datamodel_code_generator/parser/base.py
tests/data/openapi/modular.yaml
tests/parser/test_openapi.py
tests/test_main.py
tests/test_main_kr.py

Sorry to follow up with a fix so soon after the previous PR - but as the branch name sez: `modules-are-hard` :)

handle edge-case where models map to the __init__.py level of a module

---

datamodel_code_generator/parser/base.py
datamodel_code_generator/parser/jsonschema.py
tests/data/jsonschema/nested_person.json
tests/parser/test_openapi.py
tests/test_main.py

This PR fixes `as` statement on import. 
https://github.com/koxudaxi/datamodel-code-generator/issues/102

fix as statement on import

---

README.md
datamodel_code_generator/model/pydantic/types.py
datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/types.py
docs/support-data-types.md

https://github.com/koxudaxi/datamodel-code-generator/issues/30

support hostname

---

.github/ISSUE_TEMPLATE/bug_report.md

update for the bug report template

more appropriate bug_report template

---

datamodel_code_generator/parser/jsonschema.py
tests/data/openapi/nested_anyof.yaml
tests/parser/test_openapi.py

This PR fixes invalid code generation when `anyof` in array fields.
https://github.com/koxudaxi/datamodel-code-generator/issues/142

fix anyof in array fields

---

datamodel_code_generator/model/base.py
datamodel_code_generator/model/pydantic/base_model.py
datamodel_code_generator/model/template/pydantic/BaseModel.jinja2
datamodel_code_generator/parser/jsonschema.py
tests/model/pydantic/test_base_model.py
tests/parser/test_jsonschema.py

##Related issue 
https://github.com/koxudaxi/datamodel-code-generator/issues/158

fix defualt

---

datamodel_code_generator/parser/jsonschema.py
tests/data/jsonschema/nested_array.json
tests/parser/test_jsonschema.py

This PR supports a nested array
https://github.com/koxudaxi/datamodel-code-generator/issues/164

support nested array

---

datamodel_code_generator/parser/jsonschema.py
tests/data/expected/main/space_and_special_characters/output.py

This PR fixes incorrect optional type on aliased_field
https://github.com/koxudaxi/datamodel-code-generator/issues/153

Fix incorrect optional type

---

datamodel_code_generator/parser/base.py
tests/parser/test_base.py
tests/test_base.py

Thanks for putting this library together.  Here's the implementation I was proposing in #174 to make the function more robust.

Implements #174

---

tests/data/expected/main/space_and_special_characters/output.py
tests/data/json/space_and_special_characters.json

https://github.com/koxudaxi/datamodel-code-generator/issues/168

add unittest for recursive json

---

datamodel_code_generator/parser/base.py
datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/parser/openapi.py
tests/data/expected/parser/openapi/openapi_parser_parse_enum_models/output_py36.py
tests/data/expected/parser/openapi/openapi_parser_parse_enum_models/output_py37.py
tests/data/openapi/enum_models.yaml

This PR fixes the resolving name of models and fix parsing enum for duplicate names.
https://github.com/koxudaxi/datamodel-code-generator/issues/145

Fix model names

---

datamodel_code_generator/parser/jsonschema.py
tests/parser/test_openapi.py

Added as a string, something more path like via a `ConstrainedStr` might be an improvement in the future. Let me know if I should add some tests somewhere, I didn't see any for the `uri`.

Add uri-reference

---

datamodel_code_generator/parser/jsonschema.py

This covers this case:
{"some_data": "123"}

Added support of integer in string

---

setup.cfg

https://github.com/koxudaxi/datamodel-code-generator/issues/195

change dependency versions

---

datamodel_code_generator/parser/jsonschema.py
tests/data/expected/parser/openapi/openapi_parser_parse_any/output.py
tests/data/openapi/any.yaml
tests/parser/test_jsonschema.py
tests/parser/test_openapi.py

This PR supports Any type.
https://github.com/koxudaxi/datamodel-code-generator/issues/205

support any

---

datamodel_code_generator/parser/jsonschema.py
tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/format.py
tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/with_import.py
tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/with_import_format.py
tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/with_import_format_custom_module.Base.py
tests/data/openapi/additional_properties.yaml

https://github.com/koxudaxi/datamodel-code-generator/issues/210

Fix additional properties

---

datamodel_code_generator/parser/jsonschema.py
tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/format.py
tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/with_import.py
tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/with_import_format.py
tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/with_import_format_custom_module.Base.py
tests/data/openapi/additional_properties.yaml

This PR fix nested additional properties
https://github.com/koxudaxi/datamodel-code-generator/issues/225

fix nested additional properties

---

.github/ISSUE_TEMPLATE/bug_report.md

`Verison` -> Version` and lower-casing for consistency

Fix typos in issue template

---

datamodel_code_generator/parser/jsonschema.py
tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/format.py
tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/with_import.py
tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/with_import_format.py
tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/with_import_format_custom_module.Base.py
tests/data/openapi/additional_properties.yaml

https://github.com/koxudaxi/datamodel-code-generator/issues/229

Fix arrays in additional properties

---

datamodel_code_generator/model/base.py
datamodel_code_generator/model/pydantic/custom_root_type.py
datamodel_code_generator/model/template/pydantic/BaseModel_root.jinja2
datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/types.py
tests/data/expected/main/main_with_field_constraints/output.py
tests/data/expected/main/main_without_field_constraints/output.py
tests/data/openapi/api_constrained.yaml
tests/model/pydantic/test_custom_root_type.py
tests/parser/test_jsonschema.py

This PR fixes handling field constraints
https://github.com/koxudaxi/datamodel-code-generator/issues/239

fix handling field constraints

---

datamodel_code_generator/parser/jsonschema.py
tests/parser/test_jsonschema.py

https://github.com/koxudaxi/datamodel-code-generator/issues/244

support unix-time

---

datamodel_code_generator/__init__.py
datamodel_code_generator/__main__.py
datamodel_code_generator/parser/base.py
datamodel_code_generator/parser/jsonschema.py

https://github.com/koxudaxi/datamodel-code-generator/issues/242

change use_default_on_required_field to apply_default_values_for_required_fields

---

scripts/format.sh
scripts/lint.sh
setup.cfg

https://github.com/koxudaxi/fastapi-code-generator/issues/60

remove version limit of black

---

datamodel_code_generator/parser/base.py

https://github.com/koxudaxi/fastapi-code-generator/issues/64

fix a condition of importing annotations

---

README.md
docs/index.md
docs/support-data-types.md

https://github.com/koxudaxi/datamodel-code-generator/issues/266

add target source files on documents

---

datamodel_code_generator/parser/base.py
tests/data/expected/parser/openapi/openapi_parser_parse_allof/output.py
tests/data/openapi/allof.yaml

https://github.com/koxudaxi/datamodel-code-generator/pull/203

fix resolving base class order

---

datamodel_code_generator/parser/jsonschema.py
tests/data/expected/parser/openapi/openapi_parser_parse_anyof/output.py
tests/data/openapi/anyof.yaml

- https://github.com/koxudaxi/datamodel-code-generator/issues/244

Fix type in anyof

---

datamodel_code_generator/model/pydantic/base_model.py

https://github.com/koxudaxi/datamodel-code-generator/pull/328

Remove unused condition

---

datamodel_code_generator/parser/jsonschema.py
tests/data/expected/main/main_openapi_nullable/output.py
tests/data/expected/main/main_openapi_nullable_strict_nullable/output.py
tests/data/openapi/nullable.yaml

https://github.com/koxudaxi/datamodel-code-generator/issues/327

Improve strict-nullable

---

datamodel_code_generator/parser/jsonschema.py
tests/data/expected/main/main_openapi_enum_models_all/output.py
tests/data/expected/main/main_openapi_enum_models_one/output.py
tests/data/expected/parser/openapi/openapi_parser_parse_enum_models/output_py36.py
tests/data/expected/parser/openapi/openapi_parser_parse_enum_models/output_py37.py
tests/data/openapi/enum_models.yaml
tests/parser/test_openapi.py

https://github.com/koxudaxi/datamodel-code-generator/issues/348

Support nullable enum

---

datamodel_code_generator/__init__.py
tests/test_main.py

https://github.com/koxudaxi/datamodel-code-generator/issues/349

Generate function supports relative input path

---

datamodel_code_generator/model/base.py
datamodel_code_generator/model/enum.py
datamodel_code_generator/model/pydantic/base_model.py
datamodel_code_generator/model/pydantic/custom_root_type.py
datamodel_code_generator/model/pydantic/dataclass.py
datamodel_code_generator/parser/base.py
datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/reference.py
tests/data/expected/parser/openapi/openapi_parser_parse/with_import.py
tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/with_import.py
tests/model/pydantic/test_base_model.py
tests/model/pydantic/test_custom_root_type.py
tests/model/pydantic/test_data_class.py
tests/model/test_base.py
tests/parser/test_base.py

https://github.com/koxudaxi/datamodel-code-generator/issues/356
https://github.com/koxudaxi/datamodel-code-generator/issues/357

Model properties are generated when rendering

---

datamodel_code_generator/model/base.py
datamodel_code_generator/parser/base.py
datamodel_code_generator/reference.py
datamodel_code_generator/types.py

Resolve parent model by data_type

---

datamodel_code_generator/model/base.py
datamodel_code_generator/model/pydantic/base_model.py
datamodel_code_generator/model/pydantic/custom_root_type.py
datamodel_code_generator/model/pydantic/types.py
datamodel_code_generator/parser/base.py
datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/types.py
tests/model/pydantic/test_types.py
tests/parser/test_base.py
tests/parser/test_jsonschema.py

- https://github.com/koxudaxi/datamodel-code-generator/issues/357
- https://github.com/koxudaxi/datamodel-code-generator/issues/356

Lazy creating imports and unresolved_types

---

datamodel_code_generator/imports.py
datamodel_code_generator/model/base.py
datamodel_code_generator/parser/base.py
datamodel_code_generator/types.py

- https://github.com/koxudaxi/datamodel-code-generator/issues/357
- https://github.com/koxudaxi/datamodel-code-generator/issues/356

Change all imports return  type to iterator[Import]

---

datamodel_code_generator/model/pydantic/__init__.py
datamodel_code_generator/parser/base.py
datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/reference.py
datamodel_code_generator/types.py
tests/test_imports.py

- https://github.com/koxudaxi/datamodel-code-generator/issues/356
- https://github.com/koxudaxi/datamodel-code-generator/issues/357

Improve coding style

---

datamodel_code_generator/parser/jsonschema.py
tests/data/openapi/x_enum_varnames.yaml
tests/parser/test_openapi.py

https://github.com/koxudaxi/datamodel-code-generator/issues/371

Fix x-enum-varnames for string

---

datamodel_code_generator/model/base.py
datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/reference.py
tests/model/pydantic/test_base_model.py

https://github.com/koxudaxi/datamodel-code-generator/issues/385

Remove field name validator

---

datamodel_code_generator/model/base.py
datamodel_code_generator/parser/jsonschema.py
tests/data/expected/main/main_modular/collections.py
tests/data/expected/main/main_modular/foo/bar.py
tests/data/expected/main/main_modular_reuse_model/collections.py
tests/data/expected/main/main_modular_reuse_model/foo/bar.py
tests/data/expected/main/main_use_generic_container_types/collections.py
tests/data/expected/main/main_use_generic_container_types/foo/bar.py
tests/data/expected/main/main_use_generic_container_types_standard_collections/collections.py
tests/data/expected/main/main_use_generic_container_types_standard_collections/foo/bar.py
tests/data/expected/main/main_use_standard_collections/collections.py
tests/data/expected/main/main_use_standard_collections/foo/bar.py
tests/data/expected/main_kr/main_modular/collections.py
tests/data/expected/main_kr/main_modular/foo/bar.py
tests/data/expected/parser/openapi/openapi_parser_parse_modular/collections.py
tests/data/expected/parser/openapi/openapi_parser_parse_modular/foo/bar.py
tests/data/openapi/modular.yaml

https://github.com/koxudaxi/datamodel-code-generator/issues/392

Fix modular generated models

---

datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/reference.py
tests/data/jsonschema/root_id_self_ref.json
tests/test_main.py

https://github.com/koxudaxi/datamodel-code-generator/issues/379

Fix resolving ref with root id

---

datamodel_code_generator/__init__.py
datamodel_code_generator/parser/base.py
datamodel_code_generator/parser/jsonschema.py
tests/test_main.py

https://github.com/koxudaxi/datamodel-code-generator/issues/379

Support custom_class_name_generator

---

datamodel_code_generator/model/pydantic/base_model.py
datamodel_code_generator/parser/jsonschema.py
tests/data/expected/main/main_root_model_with_additional_properties/output.py
tests/data/expected/main/main_root_model_with_additional_properties_custom_class_name/output.py
tests/data/expected/main/main_root_model_with_additional_properties_literal/output.py
tests/data/expected/main/main_root_model_with_additional_properties_use_generic_container_types/output.py
tests/data/expected/main/main_root_model_with_additional_properties_use_standard_collections/output.py
tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/format.py
tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/with_import.py
tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/with_import_format.py
tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/with_import_format_custom_module.Base.py
tests/data/jsonschema/root_model_with_additional_properties.json

https://github.com/koxudaxi/datamodel-code-generator/issues/409

Improve parsing additionalProperties

---

tests/data/expected/main/main_json_reuse_enum/output.py
tests/data/expected/main/main_json_reuse_enum_default_member/output.py

https://github.com/koxudaxi/datamodel-code-generator/pull/430

Fix unittest

---

datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/reference.py
tests/data/expected/main/main_invalid_enum_name/output.py
tests/data/expected/main/main_jsonschema_field_extras_field_include_all_keys/output.py
tests/data/jsonschema/extras.json
tests/data/jsonschema/invalid_enum_name.json

https://github.com/koxudaxi/datamodel-code-generator/issues/455

Validate pydantic field name

---

pyproject.toml
setup.cfg
setup.py

- https://github.com/koxudaxi/datamodel-code-generator/issues/457

Support PEP-517

---

setup.cfg

- https://github.com/koxudaxi/datamodel-code-generator/issues/463

Support jinja2 version3

---

datamodel_code_generator/model/pydantic/base_model.py
datamodel_code_generator/parser/jsonschema.py
tests/data/expected/main/main_external_definitions/output.py
tests/data/expected/main/main_json_pointer/output.py
tests/data/expected/main/main_jsonschema_complex_any_of/output.py
tests/data/expected/main/main_jsonschema_complex_one_of/output.py
tests/data/expected/main/main_nested_json_pointer/output.py
tests/data/expected/main/multiple_files_json_pointer/file_a.py
tests/data/expected/main/multiple_files_json_pointer/file_b.py
tests/data/expected/main/multiple_files_json_pointer/file_c.py
tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/format.py
tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/with_import.py
tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/with_import_format.py
tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/with_import_format_custom_module.Base.py
tests/data/openapi/additional_properties.yaml

closes https://github.com/koxudaxi/datamodel-code-generator/issues/471

Support false on additionalProperties

---

datamodel_code_generator/parser/openapi.py

Fix invalid generated code with openapi validator

---

.github/workflows/test.yml
datamodel_code_generator/model/base.py
datamodel_code_generator/types.py
tests/data/expected/main/main_json_reuse_enum/output.py
tests/data/expected/main/main_json_reuse_enum_default_member/output.py
tests/data/jsonschema/duplicate_enum.json

https://github.com/koxudaxi/datamodel-code-generator/issues/504

Fix reuse_model for nested model

---

datamodel_code_generator/__init__.py
datamodel_code_generator/__main__.py
datamodel_code_generator/http.py
datamodel_code_generator/parser/base.py
datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/parser/openapi.py
tests/parser/test_jsonschema.py
tests/test_main.py

https://github.com/koxudaxi/datamodel-code-generator/issues/490

Support --http_headers for authorization

---

datamodel_code_generator/reference.py
tests/data/expected/main/main_jsonschema_special_field_name/output.py
tests/data/jsonschema/special_field_name.json

https://github.com/koxudaxi/datamodel-code-generator/issues/549

Fix a bug for # field

---

docs/using_as_module.md

fixes https://github.com/koxudaxi/datamodel-code-generator/issues/508

documented installation via pip

---

datamodel_code_generator/__init__.py
tests/test_main.py

This PR fixes the problem that you can't create models from json data where is in HTTP 
https://github.com/koxudaxi/datamodel-code-generator/issues/600

Fix json type form http

---

.github/workflows/test.yml
datamodel_code_generator/__main__.py
datamodel_code_generator/format.py

* Always return a `Path` object (instead of the tuple returned by `Black>=22.1.0`
Closes #700

[Fix] Support Black 22.1.0

---

datamodel_code_generator/model/pydantic/base_model.py
datamodel_code_generator/types.py
tests/data/expected/main/main_disable_appending_item_suffix/output.py
tests/data/expected/main/main_use_annotated_with_field_constraints/output.py
tests/data/expected/main/main_with_field_constraints/output.py
tests/data/expected/main/main_without_field_constraints/output.py
tests/data/openapi/api_constrained.yaml

https://github.com/koxudaxi/datamodel-code-generator/issues/583

Fix field constraint value

---

datamodel_code_generator/model/pydantic/base_model.py
datamodel_code_generator/parser/jsonschema.py
tests/data/expected/main/main_disable_appending_item_suffix/output.py
tests/data/expected/main/main_use_annotated_with_field_constraints/output.py
tests/data/expected/main/main_with_field_constraints/output.py
tests/data/expected/main/main_without_field_constraints/output.py
tests/data/openapi/api_constrained.yaml

https://github.com/koxudaxi/datamodel-code-generator/issues/719

Support unique_items

---

datamodel_code_generator/parser/jsonschema.py
tests/parser/test_jsonschema.py

Hi @koxudaxi, this works as expected to support #837, though I have no idea if this should be handled elsewhere

Support discriminators

---

datamodel_code_generator/reference.py
tests/data/expected/main/main_invalid_enum_name/output.py
tests/data/jsonschema/invalid_enum_name.json

Close: https://github.com/koxudaxi/datamodel-code-generator/issues/873

Fix mro field on enum

---

datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/parser/openapi.py
requirements-docs.txt

Closes: https://github.com/koxudaxi/datamodel-code-generator/issues/895

Fix openapi definitions schema

---

datamodel_code_generator/reference.py
tests/test_main.py

Related Issues: https://github.com/koxudaxi/datamodel-code-generator/issues/909

Fix resolving id

---

datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/reference.py
tests/data/expected/parser/openapi/openapi_parser_parse_allof_same_prefix_with_ref/output.py
tests/data/openapi/allof_same_prefix_with_ref.yaml
tests/parser/test_openapi.py

Per #714 test is needed to examplify the issue.

Fix allOf with common prefix and $ref

---

datamodel_code_generator/model/base.py
tests/data/expected/main/all_of_with_object/output.py
tests/data/jsonschema/all_of_with_object.json

Closes: https://github.com/koxudaxi/datamodel-code-generator/issues/763

Ignore duplicate name field on allOf

---

datamodel_code_generator/model/base.py
tests/data/jsonschema/person.json

Closes: https://github.com/koxudaxi/datamodel-code-generator/issues/772

Fix duplicated nested optional

---

datamodel_code_generator/reference.py
tests/test_main.py

Closes: https://github.com/koxudaxi/datamodel-code-generator/issues/1010

Fix --capitalise-enum-members

---

datamodel_code_generator/parser/jsonschema.py
tests/data/expected/main/main_jsonschema_combine_any_of_object/output.py
tests/data/expected/main/main_jsonschema_combine_one_of_object/output.py
tests/data/jsonschema/combine_any_of_object.json

Closes: https://github.com/koxudaxi/datamodel-code-generator/issues/855 https://github.com/koxudaxi/datamodel-code-generator/issues/830

Improve anyOf and oneOf detection when anyOf and oneOf parent has proprerties

---

datamodel_code_generator/__main__.py

Change default value to None

---

README.md
datamodel_code_generator/__main__.py
docs/index.md
tests/test_main.py

Closes https://github.com/koxudaxi/datamodel-code-generator/issues/1025

Add --disable-warnings

---

datamodel_code_generator/parser/base.py

Closes: https://github.com/koxudaxi/datamodel-code-generator/issues/1021

Remove dummy field

---

datamodel_code_generator/model/pydantic/base_model.py
datamodel_code_generator/parser/jsonschema.py
tests/data/jsonschema/user.json
tests/parser/test_jsonschema.py

Closes: https://github.com/koxudaxi/datamodel-code-generator/issues/1026

Support default_factory

---

datamodel_code_generator/parser/base.py
tests/data/expected/main/main_jsonschema_object_has_one_of/output.py
tests/data/expected/main/main_openapi_override_required_all_of/output.py

Closes: https://github.com/koxudaxi/datamodel-code-generator/issues/894

Remove duplicate model

---

datamodel_code_generator/parser/base.py

Closes: https://github.com/koxudaxi/datamodel-code-generator/issues/894

Fix naming logic for duplicate name model

---

datamodel_code_generator/model/base.py
datamodel_code_generator/parser/base.py

Closes: https://github.com/koxudaxi/datamodel-code-generator/issues/894#issuecomment-1413316477

Improve duplicate model detection

---

datamodel_code_generator/http.py
datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/reference.py
tests/parser/test_jsonschema.py
tests/test_main.py

Closes: https://github.com/koxudaxi/datamodel-code-generator/issues/1109

Fix url $id

---

docs/using_as_module.md

Related Issues: https://github.com/koxudaxi/datamodel-code-generator/issues/803

Add output model type description to documents

---

datamodel_code_generator/model/pydantic/types.py
datamodel_code_generator/types.py
tests/model/pydantic/test_types.py

Closes: https://github.com/koxudaxi/datamodel-code-generator/issues/1362

Fix condecimal

---

.github/workflows/test.yml
datamodel_code_generator/model/base.py
datamodel_code_generator/model/dataclass.py
datamodel_code_generator/model/msgspec.py
datamodel_code_generator/model/pydantic/base_model.py
datamodel_code_generator/model/pydantic_v2/base_model.py
datamodel_code_generator/model/typed_dict.py
datamodel_code_generator/reference.py
datamodel_code_generator/types.py

Closes: https://github.com/koxudaxi/datamodel-code-generator/issues/1601

Avoid pydantic ClassVar bug

---

datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/parser/openapi.py
tests/data/expected/main/main_openapi_nullable/output.py
tests/data/expected/main/main_openapi_nullable_strict_nullable/output.py
tests/data/expected/main/main_openapi_nullable_strict_nullable_use_union_operator/output.py
tests/data/expected/main/main_typed_dict_nullable/output.py
tests/data/expected/main/main_typed_dict_nullable_strict_nullable/output.py
tests/data/expected/main/main_use_default_kwarg/output.py
tests/data/openapi/nullable.yaml

This PR improves the fix in the PR.
https://github.com/koxudaxi/datamodel-code-generator/pull/1648

Move nullable logic to openapi parser

---

datamodel_code_generator/types.py
tests/data/expected/main/main_strict_types/output.py
tests/data/expected/main/main_strict_types_all/output.py
tests/data/expected/main/main_strict_types_all_field_constraints/output.py
tests/data/jsonschema/strict_types.json

Closes: https://github.com/koxudaxi/datamodel-code-generator/issues/1378

Fix exponent in minimum

---

README.md
datamodel_code_generator/__init__.py
datamodel_code_generator/arguments.py
datamodel_code_generator/http.py
datamodel_code_generator/parser/openapi.py
docs/index.md
poetry.lock
pyproject.toml
tests/test_main.py

Related Issues: https://github.com/koxudaxi/datamodel-code-generator/issues/1671 https://github.com/koxudaxi/datamodel-code-generator/issues/1649

Change --validation option to optional

---

poetry.lock
pyproject.toml

This dependency was not specified in `pyproject.toml`. Resolves #1697

Add pyyaml

---

datamodel_code_generator/model/pydantic_v2/base_model.py
tests/data/expected/main/main_jsonschema_field_extras/output.py
tests/data/expected/main/main_jsonschema_field_extras_field_extra_keys/output.py
tests/data/expected/main/main_jsonschema_field_extras_field_extra_keys_v2/output.py
tests/data/expected/main/main_jsonschema_field_extras_field_include_all_keys/output.py
tests/data/expected/main/main_jsonschema_field_extras_field_include_all_keys_v2/output.py
tests/data/expected/main/main_jsonschema_field_extras_v2/output.py
tests/data/jsonschema/extras.json
tests/test_main.py

Fixes: https://github.com/koxudaxi/datamodel-code-generator/issues/1701

Change example to examples in pydantic_v2

---

datamodel_code_generator/model/pydantic/base_model.py
datamodel_code_generator/model/pydantic_v2/base_model.py
tests/data/expected/main/main_jsonschema_field_extras_field_extra_keys/output.py
tests/data/expected/main/main_jsonschema_field_extras_field_extra_keys_v2/output.py
tests/data/expected/main/main_jsonschema_field_extras_field_include_all_keys_v2/output.py
tests/data/expected/main/main_jsonschema_field_extras_v2/output.py

Closes: https://github.com/koxudaxi/datamodel-code-generator/issues/1680

Support json_schema_extra

---

datamodel_code_generator/model/base.py
tests/model/pydantic/test_constraint.py

currently has_constraints will be False if all the set constraints are falsy (0)

has_constraints should return true for falsy values

---

datamodel_code_generator/__main__.py
datamodel_code_generator/parser/base.py

Currently the config and args don't combine if they are sequences or dictionaries. This serves to fix that

Fix merging config and args

---

.github/workflows/test.yml
datamodel_code_generator/__init__.py
datamodel_code_generator/pydantic_patch.py
datamodel_code_generator/util.py
poetry.lock
pyproject.toml

Related Issues: https://github.com/koxudaxi/datamodel-code-generator/pull/1509/files

Drop support python 3.7 on runtime

---

datamodel_code_generator/parser/base.py
tests/parser/test_base.py

Closes: https://github.com/koxudaxi/datamodel-code-generator/issues/1850

Escape null character

---

datamodel_code_generator/model/enum.py
tests/parser/test_base.py

Closes: https://github.com/koxudaxi/datamodel-code-generator/issues/2255

enum find member quote handling

---

datamodel_code_generator/types.py
tests/main/test_types.py

Closes: https://github.com/koxudaxi/datamodel-code-generator/issues/2191

fix Literal imports

---

.github/workflows/test.yml
datamodel_code_generator/__init__.py
datamodel_code_generator/__main__.py
datamodel_code_generator/format.py
datamodel_code_generator/http.py
datamodel_code_generator/model/__init__.py
datamodel_code_generator/model/base.py
datamodel_code_generator/model/enum.py
datamodel_code_generator/model/pydantic/base_model.py
datamodel_code_generator/model/pydantic/types.py
datamodel_code_generator/model/pydantic_v2/base_model.py
datamodel_code_generator/model/pydantic_v2/types.py
datamodel_code_generator/parser/base.py
datamodel_code_generator/parser/graphql.py
datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/parser/openapi.py
datamodel_code_generator/pydantic_patch.py
datamodel_code_generator/reference.py
datamodel_code_generator/types.py
datamodel_code_generator/util.py
pyproject.toml
tox.ini
uv.lock

Related Issues: https://github.com/koxudaxi/datamodel-code-generator/pull/2292

Migrate mypy to pyright

---

.github/workflows/publish.yml

I setup the config.
Also, I add the config to PyPI console.
https://docs.pypi.org/trusted-publishers/using-a-publisher/

setup-trusted-publisher

---

README.md
docs/index.md
pyproject.toml
src/datamodel_code_generator/__init__.py
src/datamodel_code_generator/__main__.py
src/datamodel_code_generator/arguments.py
src/datamodel_code_generator/format.py
src/datamodel_code_generator/parser/base.py
src/datamodel_code_generator/parser/graphql.py
src/datamodel_code_generator/parser/jsonschema.py
src/datamodel_code_generator/parser/openapi.py
tests/test_format.py
uv.lock

Closes: https://github.com/koxudaxi/datamodel-code-generator/issues/2025 https://github.com/koxudaxi/datamodel-code-generator/issues/1643

feat: add ruff formatters

---

src/datamodel_code_generator/model/enum.py

Fix https://github.com/koxudaxi/datamodel-code-generator/issues/2353

Ensure we have a string before trying to strip

---

pyproject.toml
uv.lock

* Update `pyproject.toml`
* Update `uv.lock`

Bump upper version limit on the inflect library from 6 to 8

---

src/datamodel_code_generator/__main__.py
src/datamodel_code_generator/util.py

Fixes https://github.com/koxudaxi/datamodel-code-generator/issues/2471

Fix Pydantic `@model_validator()` usage  for Pydantic 2.12
