.travis.yml
README.md

This will build and deploy packages to PyPI for each tag (as long as the tests pass (just one dummy test at the moment)
To get this working, this will require input from @koxudaxi to:
1. enable this project in TravisCI.org
2. generate the encrypted password for their PyPI account:
```
$ gem install travis # or gem install --user travis
$ git fetch origin pull/6/head:pypi
$ git checkout pypi
$ travis encrypt "your-password-here" --add deploy.password
```
This will update the `.travis.yml` - you can push it back to this branch/PR or if you post the encrypted password here I'll add it to the PR :)
Closes #5

add travis config to deploy PyPI packge

---

datamodel_code_generator/parser/openapi.py
tests/data/api.yaml
tests/parser/test_openapi.py
tests/test_main.py

The PR fixes to parse referencing external object on a object.
eg: 
```python
Result:
type: object
properties:
event:
$ref: '#/components/schemas/Event'
```

fix to parse ref on object

---

datamodel_code_generator/parser/openapi.py
tests/data/duplicate_models.yaml
tests/parser/test_openapi.py

The PR improve generating list object from an array.
the code generator creates a custom root object from an array.
However, the code generator should not create a custom root object from an array of inside an object.
The PR works to creates List's fields on an object.
Before
```python
class Item(BaseModel):
name: str
class Items(BaseModel):
__root__:  List[Item]
class Bucket(BaseModel):
items: Items
```
After
```python
class Item(BaseModel):
name: str
class Bucket(BaseModel):
items: List[item]
```

Improve generating list object

---

README.md
datamodel_code_generator/__init__.py
datamodel_code_generator/__main__.py
datamodel_code_generator/parser/openapi.py
setup.cfg

The PR supports to show debug message.
The option is enabled by cli argument.
```
datamodel-codegen --help                                       
usage: datamodel-codegen [-h] [--input INPUT] [--output OUTPUT]
[--base-class BASE_CLASS]
[--target-python-version {3.6,3.7}] [--debug]
optional arguments:
-h, --help            show this help message and exit
--input INPUT         Open API YAML file (default: stdin)
--output OUTPUT       Output file (default: stdout)
--base-class BASE_CLASS
Base Class (default: pydantic.BaseModel)
--target-python-version {3.6,3.7}
target python version (default: 3.7)
--debug               show debug message
```

add debug mode

---

datamodel_code_generator/imports.py
datamodel_code_generator/model/base.py
datamodel_code_generator/model/pydantic/types.py
datamodel_code_generator/parser/openapi.py
datamodel_code_generator/types.py
tests/model/pydantic/test_types.py
tests/parser/test_openapi.py
tests/test_main.py

also allows more than one import for `DataType` (required to support `Dict[str, Any]` for example)

Add missing imports for `constr` and `Dict[str, Any]`

---

datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/parser/openapi.py
tests/data/enum_models.yaml
tests/parser/test_openapi.py

The PR supports alias of an enum which uses  `x-enum-varnames`
https://openapi-generator.tech/docs/templating#enum

Support enum alias

---

datamodel_code_generator/parser/openapi.py
setup.cfg
tests/data/modular.yaml
tests/parser/test_openapi.py
tests/test_main.py

For `anyOf` properties where the type is primitive (int, float, bool,
str, etc), produce a `Union` of primitive types without creating a
special "singular name" type

Support for Primitve union properties

---

datamodel_code_generator/parser/jsonschema.py

- `is_object` is masking `anyOf`/`allOf` logic preventing creation of `Union` fields

Move logic for anyOf/allOf to higher priority

---

datamodel_code_generator/parser/jsonschema.py
tests/data/openapi/modular.yaml
tests/parser/test_openapi.py
tests/test_main.py
tests/test_main_kr.py

- map `{"type": "array", "items": {"type": primitive_type}}` to `List[py_primitive_type]`
in `anyOf`

add support for arrays of simple primities to anyOf

---

datamodel_code_generator/model/pydantic/types.py
tests/model/pydantic/test_types.py
tests/parser/test_jsonschema.py
tests/parser/test_openapi.py
tests/test_main.py

This change aligns mapping from json schema to pydantic Field arguments.
See https://pydantic-docs.helpmanual.io/usage/schema/#field-customisation

Change numeric constraints to correct mapping

---

.gitignore
datamodel_code_generator/__main__.py
datamodel_code_generator/format.py
datamodel_code_generator/model/base.py
datamodel_code_generator/parser/base.py
datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/parser/openapi.py
datamodel_code_generator/types.py
pyproject.toml
scripts/lint.sh
setup.cfg
tests/model/pydantic/test_types.py
tests/model/test_base.py
tests/parser/test_base.py
tests/parser/test_jsonschema.py
tests/parser/test_openapi.py
tests/test_main.py
tests/test_main_kr.py

move lint configuration (black, isort, mypy) to configuration files (pyproject.toml, setup.cfg) to play nicer with other dev environemnts

move lint configuration (black, isort, mypy) to configuration files

---

README.md
datamodel_code_generator/format.py
tests/data/project/pyproject.toml

Fixing `skip-string-normalization` option to be in the right direction (negative rather than positive) to match the _actual_ configuration item name in Black
(sorry - the config file option is the opposite to the library option)

correct string-normalization to skip-string-normalization

---

datamodel_code_generator/parser/jsonschema.py
tests/parser/test_openapi.py

The PR supports array of type attributes on jsonschema.
https://github.com/koxudaxi/datamodel-code-generator/issues/102

Support array of type attribute on jsonschema 

---

datamodel_code_generator/model/pydantic/types.py
datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/types.py
tests/data/jsonschema/person.json
tests/test_main.py

This PR supports empty array on JsonSchema
https://github.com/koxudaxi/datamodel-code-generator/issues/111

support empty array

---

datamodel_code_generator/model/pydantic/types.py
tests/model/pydantic/test_types.py

Proposed workaround to fix parse error when declaring regex. (https://github.com/koxudaxi/datamodel-code-generator/issues/124)

Fix parse errors when property pattern is explicit.

---

datamodel_code_generator/model/pydantic/types.py
docs/jsonschema.md
tests/model/pydantic/test_types.py
tests/parser/test_jsonschema.py
tests/parser/test_openapi.py
tests/test_main.py

`conint` args have to be int.
`confloat` args have to be  float.

Fix args of conint and confloat

---

datamodel_code_generator/model/base.py
datamodel_code_generator/model/pydantic/base_model.py

Make `DataModelField` generate it's string value dynamically instead of at creation time.
I have a few special cases and I want to avoid forking `datamodel-code-generator`, so my approach is currently like this: I have my own parser subclassing `JsonSchemaParser`:
```python
class K8SParser(JsonSchemaParser):
def parse_raw(self):
super(K8SParser, self).parse_raw()
```
I understand that the project is not meant to be used like this but hope my change is welcome anyway as it makes my use case easier :)

dynamic field serialization

---

datamodel_code_generator/parser/base.py
datamodel_code_generator/parser/jsonschema.py
tests/data/openapi/array_enum.yaml
tests/parser/test_openapi.py

This PR supports enum in array
https://github.com/koxudaxi/datamodel-code-generator/issues/148

support enum in array

---

datamodel_code_generator/model/base.py
datamodel_code_generator/parser/jsonschema.py
tests/model/test_base.py

This PR fixes multiple sub-type in List
before:
```python
List[str, int, float]
```
after:
```python
List[Union[str, int, float]]
```

Fix multiple sub-type in List

---

tests/parser/test_openapi.py

cleaning up the test for better readability, especially on test failure.

clenaup openapi_parser_parse_alias test

---

README.md
datamodel_code_generator/parser/base.py
datamodel_code_generator/parser/jsonschema.py
docs/index.md
docs/support-data-types.md
setup.cfg
tests/data/jsonschema/user.json
tests/parser/test_jsonschema.py

This PR adds supporting remote `$ref`.
The feature is optional.  Users have to install http extra blow.
```bash
$ pip install datamodel_code_generator[http]
```
https://github.com/koxudaxi/datamodel-code-generator/issues/156

Support remote ref

---

datamodel_code_generator/model/pydantic/imports.py

This typo breaks import of generated models.

Fixes typo in import name of condecimal

---

docs/field-constraints.md

It looks like the bash examples were backwards for the with/without `--field-constraints`, I just swapped them.

Fixed misreferenced examples in the docs.

---

datamodel_code_generator/reference.py
tests/test_reference.py

Whilst calculating relative paths, the current implementation has an
issue where if a subfolder beyond the point of divergence has the same
name in the base_path and the target_path, this doesn't increment the
parent_count, and doesn't properly append to the children.
Example:
>   base_path: /a/b/c/d
>   target_path: /a/b/e/d
> 
>   To get from the base path to the target path, we'd need to go up 2
>   directories from d to b, then back down through e and into d, so we
>   expect the function to return "../../e/d"
> 
>   In the current implementation of get_relative_path, we successfully
>   `continue` through `a` and `b`, as these match the condition
>   `if base_part == target_part`.
> 
>   Once we get to the comparison between `c` and `e`, we increment the
>   parent_count, showing …

Fix get_relative_path subfolders with same names

---

datamodel_code_generator/parser/jsonschema.py
tests/data/expected/main/main_openapi_enum_models_all/output.py
tests/data/expected/main/main_openapi_enum_models_as_literal_py37/output.py
tests/data/expected/main/main_openapi_enum_models_one/output.py
tests/data/expected/parser/openapi/openapi_parser_parse_enum_models/output_py36.py
tests/data/expected/parser/openapi/openapi_parser_parse_enum_models/output_py37.py
tests/data/openapi/enum_models.yaml

This is a fix for https://github.com/koxudaxi/datamodel-code-generator/issues/424
Checked
- `./scripts/test.sh`
- `./scripts/format.sh`
- `./scripts/lint.sh` (I am getting some errors here but no files related to this change)
```
datamodel_code_generator/format.py:54: error: Module has no attribute "__version__"
datamodel_code_generator/format.py:57: error: Module has no attribute "Config"
datamodel_code_generator/format.py:67: error: Module has no attribute "__version__"
datamodel_code_generator/format.py:70: error: Module has no attribute "SortImports"
datamodel_code_generator/format.py:77: error: Module has no attribute "code"
```

Handle nested nullable enums

---

datamodel_code_generator/parser/jsonschema.py

This way, user can provide a customized jinja template specific to enum
Fixes #428

Pass custom template dir when creating enums

---

datamodel_code_generator/parser/base.py

When looking for model to reuse, pin a list of enum models that have been swapped; them remove them after the fact.
Fixes #429

Don't generate enum models that have been swapped by a reused model

---

README.md

Due to a minor error, the yaml was not highlighted. I think the maintainers wanted to get it highlighted.
**Old**
**New**

Modify README.md to correct the code highlighting for yaml

---

datamodel_code_generator/types.py

This change adds support for `integer` inline enums. It fixes #440.
The following schema:
```yml
Foo:
type: object
properties:
bar:
type: integer
enum: [1]
```
Becomes the following model:
```py
class Foo(BaseModel):
bar: Optional[Literal[1]] = None
```
And the following schema:
```yml
Foo:
type: object
properties:
bar:
type: string
enum: ["a"]
```
Becomes the following model:
```py
class Foo(BaseModel):
bar: Optional[Literal['a']] = None

Fix inline enum only string literal

---

datamodel_code_generator/types.py
tests/data/expected/main/main_openapi_enum_models_all/output.py
tests/data/expected/main/main_openapi_enum_models_as_literal_py37/output.py
tests/data/expected/main/main_openapi_enum_models_one/output.py
tests/data/expected/parser/openapi/openapi_parser_parse_enum_models/output_py36.py
tests/data/expected/parser/openapi/openapi_parser_parse_enum_models/output_py37.py
tests/data/openapi/enum_models.yaml
tests/parser/test_openapi.py
tests/test_main.py

Fixes #688
Before, dependening on the exact version of libraries imported before
parsing `types.py`, literal integers would get converted to strings,
as python caches specified generics and considers
`Union[int, str] == Union[str, int]` to be true.

do not convert literal int to string

---

docs/development-contributing.md

It looks like this should read `poetry`, not `poeyry`!

[Docs] Fix typo

---

datamodel_code_generator/format.py
tests/test_format.py

This pull request adds Python 3.10 to the PythonVersion enum so that it can also be constructed for it.
There's also a simple test that has been added to ensure the enum covers the version of Python being tested.
The test has been put in its own file following the model of `test_imports.py`.
The test is not parametrized as it goals is to fail if a new version of Python is tested but has not yet been added to the enum.

Add Python 3.10 to PythonVersion

---

datamodel_code_generator/reference.py
datamodel_code_generator/types.py
poetry.lock

Fix for #810 due to deep copy introduction in Pydantic.
It seems like pydantic 1.9.1 added deepcopy to model validation:
```
Config.copy_on_model_validation does a deep copy and not a shallow one, https://github.com/samuelcolvin/pydantic/issues/3641
```
(from the [release notes](https://github.com/pydantic/pydantic/releases/tag/v1.9.1))
Current tests fail with a simple `poetry upgrade`.
<details>
```
poetry run ./scripts/test.sh
================================================================================================ test session starts ================================================================================================
platform darwin -- Python 3.10.3, pytest-7.0.1, pluggy-1.0.0
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 …
```

Fix deep copy max recursion failure - pydantic 1.9.1

---

datamodel_code_generator/format.py

Since `PythonVersion` members are `str`, for `PythonVersion.PY_310` - `"3.10"`, the comparison `PY_310 >= self.PY_38.value` evaluated to `False`

fix(format): Fix PythonVersion.has_literal_type for Python 3.10.

---

datamodel_code_generator/parser/jsonschema.py

For example it fixes generating fields of type `Decimal` if format is set to `decimal` in JSON schema.
Following example
```json
{
"properties": {
"rate": {
"type": "number",
"format": "decimal"
}
}
}
```
will produce following field within pydantic model (after the fix):
```python
rate: Optional[Decimal] = None
```
previously it produced:
```python
rate: Optional[float] = None
```

Use format of object if provided

---

datamodel_code_generator/parser/base.py

Reference: #892
Code generator is appending a dot at end of module name in import statement, which is throwing an error with black. Maybe the dot can be prepended since it is indicating path heirarchy levels?

Fix generating import statement code

---

datamodel_code_generator/reference.py
datamodel_code_generator/types.py
poetry.lock
pyproject.toml

Reduces Pytest warnings from 6145 down to 4.

Fix deprecation warnings around "copy_on_model_validation"

---

datamodel_code_generator/__main__.py
datamodel_code_generator/format.py
datamodel_code_generator/types.py

`from __future__ import annotations` works fine for union operator.
target python 3.6 don't add `from __future__ import annotations` . But 3.6 is EOL, we can ignore the verison.

Remove union operator error when target-python is 3.9 or early version

---

datamodel_code_generator/model/pydantic/base_model.py

@dataclass_transform supports both default_factory and default on fields, so if default_factory is present no need to add default
Fixes #1146

Exclude fields with default_factory from --use-default-kwarg

---

datamodel_code_generator/__init__.py

The [docs](https://koxudaxi.github.io/datamodel-code-generator/using_as_module/) mention importing generate and InputFileType, so those should be listed in __all__. While we're here, also expose error types so users can write proper exception handlers.

Update __all__ to expose needed types

---

poetry.lock
pyproject.toml

This is a follow up to #1222.
Typed-ast is a very painful dependency, I'm not sure why it is included in the dependencies to begin with. Modern versions of black and mypy no longer use typed-ast.

(🎁) remove typed-ast dependency

---

datamodel_code_generator/__init__.py
tests/test_main.py
tests/test_main_kr.py

As a follow up to #1248, this change improves the message to include the relevant config option

(🎁) reference config option to specify input type

---

datamodel_code_generator/parser/jsonschema.py

Fixes issue found here https://github.com/koxudaxi/datamodel-code-generator/issues/1317

Remove self attribute from jsonschema root attributes

---

datamodel_code_generator/parser/base.py

Resolve the differences in file loading caused by different operating systems, ensuring that files are loaded in the same order regardless of the OS, and making model names and field names idempotent.

Eliminate the naming differences of model names and field names by the OS

---

pyproject.toml

This PR proposes relaxing the version constraint of prance (https://pypi.org/project/prance/). This is to avoid transitive dependency issues caused by prance: Currently, users can't use this fantastic datamodel-code-generator along with Python packages that require [packaging](https://pypi.org/project/packaging/) 22.0 or newer. 
One example of such packages is Black: Black 23.1.0 or newer require packaging 22.0 or newer ([commit](https://github.com/psf/black/commit/69ca0a4c7a365c5f5eea519a90980bab72cab764)) (NOTE: in organizations that adopt [monorepo](https://en.wikipedia.org/wiki/Monorepo), they often need to use a single centralized requirements file that contain Black and datamodel-code-generator that require different versions of packaging).
There are two reasons why the dependency …

Relax version constraint of prance

---

.pre-commit-hooks.yaml

Adding support to use this as a pre-commit hook, closes https://github.com/koxudaxi/datamodel-code-generator/issues/1415

Pre-commit-hooks

---

datamodel_code_generator/model/__init__.py
datamodel_code_generator/model/pydantic_v2/__init__.py

- #1440
- Explained here https://github.com/koxudaxi/datamodel-code-generator/issues/1440#issuecomment-1660077870
- Give Pydantic V2 its own `dump_resolve_reference_action`
- change it from 'update_forward_refs' to 'model_rebuild' to eliminate warning

Give Pydantic V2 its own `dump_resolve_reference_action` to use `model_rebuild` not `update_forward_refs`

---

datamodel_code_generator/model/pydantic/types.py
datamodel_code_generator/model/pydantic_v2/types.py
tests/data/expected/main/main_pattern/output.py
tests/data/expected/main/main_pattern_pydantic_v2/output.py

The original regex causes errors when loading the generated model.
**To Reproduce**
Example schema:
```json
{
"$schema": "https://json-schema.org/draft/2020-12/schema",
"title": "Example",
"type": "object",
"properties": {
"data": {
"type": "string",
"format": "hostname"
}
}
}
```
Used commandline:
```
$ datamodel-codegen --output-model-type pydantic_v2.BaseModel --input schema.json --output model.py
$ python3 -m model
```
Output:
```
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/private/tmp/test/model.py", line 12, in <module>
class Example(BaseModel):
File "/private/tmp/test/env/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 174, in __new__ …
```

fix: Fix regex expression of hostname in pydantic v2

---

pyproject.toml

This is causing a whole rat tail of transitive dependency issues for us. We can't install `data-diff` with [Apache Airflow 2.6.3 constraints](https://raw.githubusercontent.com/apache/airflow/constraints-2.6.3/constraints-3.10.txt), because it requires dbt-artifacts-parser, which requires datamodel-code-generator, which requires openapi-spec-validator, however aforementioned constraints pin this project to 0.5.7. Would be great if this dependency could be loosened up a bit.
Analogue to #1343.

Update openapi-spec-validator to 0.5.7

---

datamodel_code_generator/model/pydantic_v2/__init__.py

In Pydantic v2, a new "feature" was introduced that warned you if your field keys began with `model_`. However we have several fields that need to be named as such. So per [Pydantic docs](https://docs.pydantic.dev/2.1/usage/model_config/#protected-namespaces), this warning can be removed by setting `protected_namespaces = ()` to remove the default protected namespace `model_`.
This PR allows an `extra_data_template` JSON file such as the following to be passed into the datamodel-codgen tool and have the `protected_namespace` change actually take affect. I verified that the warnings disappear on my project after this change.
```
{
"MyModelThatIsCausingWarnings": {
"config": {
"protected_namespaces": []
}
}
}
```

Added protect namespace to Pydantic v2 ConfigDict

---

datamodel_code_generator/__main__.py

On issue https://github.com/koxudaxi/datamodel-code-generator/issues/1027 there was a problem with CLI option defaults overriding pyproject.toml. Here's another one, `use-default-kwarg`

Add missing default=None

---

datamodel_code_generator/parser/base.py
datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/parser/openapi.py
datamodel_code_generator/reference.py
tests/data/expected/parser/openapi/openapi_parser_parse_array_called_fields_with_oneOf_items/output.py
tests/data/openapi/array_called_fields_with_oneOf_items.yaml
tests/parser/test_openapi.py
tests/test_infer_input_type.py

Adds a test to reproduce https://github.com/koxudaxi/datamodel-code-generator/issues/1508
The input yaml is the same as from the issue, and for the output I took a guess at what correct would be based on what the output is when I change the name of `components.schemas.BadSchema.properties.fields` to `fieldz`, which was:
```python
class FieldzItem(BaseModel):
a: Optional[str] = None
class FieldzItem1(BaseModel):
b: Optional[str] = Field(None, regex='^[a-zA-Z_]+$')
class BadSchema(BaseModel):
fieldz: Optional[List[Union[FieldzItem, FieldzItem1]]] = None
```

Fix class Field generated when array with name fields with oneOf inside

---

datamodel_code_generator/model/template/pydantic_v2/RootModel.jinja2
tests/data/expected/main/allow_extra_fields_pydantic_v2/output.py
tests/data/expected/main/allow_population_by_field_name_pydantic_v2/output.py
tests/data/expected/main/enable_faux_immutability_pydantic_v2/output.py
tests/data/expected/main/main_extra_template_data_config_pydantic_v2/output.py
tests/data/expected/main/main_jsonschema_custom_type_path_pydantic_v2/output.py
tests/data/expected/main/main_openapi_custom_id_pydantic_v2/output.py
tests/data/expected/main/main_openapi_custom_id_pydantic_v2_custom_base/output.py
tests/data/expected/main/main_pydantic_v2/output.py
tests/data/expected/main/main_with_field_constraints_pydantic_v2/output.py
tests/data/expected/main/main_with_field_constraints_pydantic_v2_use_generic_container_types/output.py
tests/data/expected/main/main_with_field_constraints_pydantic_v2_use_generic_container_types_set/output.py
tests/data/expected/main/main_with_field_constraints_pydantic_v2_use_standard_collections/output.py
tests/data/expected/main/main_with_field_constraints_pydantic_v2_use_standard_collections_set/output.py
tests/data/expected/main/main_without_field_constraints_pydantic_v2/output.py
tests/model/pydantic_v2/test_root_model.py

Closes: https://github.com/koxudaxi/datamodel-code-generator/issues/1491
and by extension it fixes mypy's error:
`Missing type parameters for generic type 'RootModel'`
It's not clear from the [pydantic documentation](https://docs.pydantic.dev/dev-v2/usage/models/#rootmodel-and-custom-root-types) whether they force the user to use declare the type twice. They have one example with `Pets(RootModel[List[str]])` and one with  `Pets(RootModel)`. Though `mypy` seems to be in favor of the double type hint style.

fix: add type parameters to generic RootModel

---

datamodel_code_generator/parser/jsonschema.py
datamodel_code_generator/parser/openapi.py
poetry.lock
tests/data/jsonschema/user_defs.json
tests/test_main.py

Closes:  https://github.com/koxudaxi/datamodel-code-generator/issues/1578 https://github.com/koxudaxi/datamodel-code-generator/issues/1541
https://json-schema.org/draft/2019-09/release-notes#semi-incompatible-changes
This tool is incompatible with Draft 2019-09 and cannot handle $defs.
The PR supports $defs

Support $defs for Draft 2019-09 

---

README.md
datamodel_code_generator/arguments.py
datamodel_code_generator/reference.py

Fixes #1644
@koxudaxi It seemed to me that this would be a good place. Please correct if not.
Also, I'm not that sure about the option description I suggested. But I think that it should be reformulated to prevent confusion.

Fix `--remove-special-field-name-prefix` + fields (e.g. enum members) starting with numbers

---

datamodel_code_generator/parser/jsonschema.py
tests/data/expected/main/main_typed_dict_nullable_strict_nullable/output.py

This fixes an issue where array items are not generated as `Optional`, despite adding the `nullable: true` property: https://github.com/koxudaxi/datamodel-code-generator/issues/1496
I'm not sure if this is the best way to fix it, but it works well for me.

Fix generation of nullable array items

---

datamodel_code_generator/types.py

Fix UnionIntFloat json schema generation by providing the union schema it needs.
Close #1668

Fix UnionIntFloat json schema generation.

---

datamodel_code_generator/model/pydantic_v2/base_model.py
datamodel_code_generator/parser/jsonschema.py
tests/parser/test_jsonschema.py

I don't know what the ramifications of this change are, but I know this change seems to skip the error when data classes from json schema

Fix error when JsonSchemaObject is bool with Pydantic v2

---

datamodel_code_generator/format.py
datamodel_code_generator/model/base.py
datamodel_code_generator/model/pydantic_v2/base_model.py
datamodel_code_generator/parser/jsonschema.py
tests/data/expected/main/main_jsonschema_field_extras_field_extra_keys_v2/output.py
tests/data/expected/main/main_jsonschema_field_extras_field_include_all_keys/output.py
tests/data/expected/main/main_jsonschema_field_extras_field_include_all_keys_v2/output.py
tests/data/jsonschema/extras.json

Pydantic v2 `Field` allows you to pass in extra data when generating a json-schema with `Model.model_json_schema()`.
This PR adds the `json_schema_extra` kwarg to a pydantic v2 Field with included `readOnly` and `writeOnly` values if they exist on the `JsonSchemaObject`. Now when generating with `model_json_schema()`, it will include the read/write only values on the schema.
https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.json_schema_extra

Improve json_schema_extra to pydanticv2 Field with readOnly/writeOnly 

---

datamodel_code_generator/parser/jsonschema.py
tests/parser/test_jsonschema.py

As described in #1781, I have a need to extend the `JsonSchemaParser` to handle an "extension" to JSON schema. In that discussion, I noted that I figured out method for achieving this, but it required duplication with slight alteration of code already present in the `JsonSchemaParser`.
This PR is a possible solution to avoiding that issue. It does this by factoring the direct call to the `JsonSchemaObject` out into a class variable which can be overridden to a subclass of the `JsonSchemaObject` by a sub classing the `JsonSchemaParser`. If there are better alternate solutions to this issue feel free to close this PR and suggest them in #1781.

Enable ability to use custom `JsonSchemaObject` in `JsonSchemaParser`

---

.github/workflows/test.yml
datamodel_code_generator/format.py
tests/test_main.py

Fixes: https://github.com/koxudaxi/datamodel-code-generator/issues/1853

Fix black module error when 19.10b0 is installed

---

.github/workflows/codspeed.yml
datamodel_code_generator/__init__.py
datamodel_code_generator/pydantic_patch.py

There are errors in pipelines that run the testing configuration `python=3.12` and `pydantic=1.10.9`. The error is something like:
```
| ________________ ERROR collecting tests/parser/test_openapi.py _________________
| tests/parser/test_openapi.py:10: in <module>
|     from datamodel_code_generator import OpenAPIScope, PythonVersion
| datamodel_code_generator/__init__.py:35: in <module>
|     from datamodel_code_generator.parser.base import Parser
| datamodel_code_generator/parser/base.py:37: in <module>
|     from datamodel_code_generator.model import pydantic as pydantic_model
| datamodel_code_generator/model/__init__.py:5: in <module>
|     from ..types import DataTypeManager as DataTypeManagerABC
| datamodel_code_generator/types.py:240: in <module>
|     class DataType(_BaseModel):
| …
```

patch pydantic v1.10.9 conflict with py3.12

---

README.md

Minor fix to README.md mark down to escape apostrophes in the *All Command Options* section

Escaping apostophes in mark-down

---

datamodel_code_generator/model/pydantic_v2/__init__.py

https://github.com/koxudaxi/datamodel-code-generator/discussions/466#discussioncomment-11026869
Meanwhile, I am trying to override the `ConfigDict.jinja2` template, but it doesn't work - it seems to be ignored
```
model_config = ConfigDict(
{%- for field_name, value in config.dict(exclude_unset=True).items() %}
{{ field_name }}={{ value }},
{%- endfor %}
use_enum_values=True
)
```
See https://github.com/koxudaxi/datamodel-code-generator/issues/2136

Support `use_enum_values` in `ConfigDict`

---

.pre-commit-config.yaml
poetry.lock

The `content-hash` entry was invalid.
Also added checks for poetry to pre-commit and fixed formatting of .pre-commit-config.yaml

Fix content-hash; add pre-commit-check for poetry.

---

datamodel_code_generator/parser/openapi.py

When generating OpenAPI Parameters model with custom_template_dir, it uses the default template rather than the customized one. It appears that custom_template_dir is not being passed when instantiating the class.

fix(parser): custom_template_dir not passed to data_model_type for OpenAPIScope.Parameters

---

tests/data/expected/parser/openapi/openapi_parser_parse_array_called_fields_with_oneOf_items/output.py

Following the initial setup guide resulted in one of the test cases failing with this difference in the produced output.

Fix OpenAPI test case failure in fresh clone

---

datamodel_code_generator/model/__init__.py

Default datetime class and python version

---

README.md
datamodel_code_generator/arguments.py
docs/index.md

Hi!  I'm packaging this project for inclusion into Debian, and our QA tools found a small typo nit:
```
I: datamodel-codegen: typo-in-manual-page "Allow to" "Allow one to" [usr/share/man/man1/datamodel-codegen.1.gz:155]
```
How about this patch?
Debian packages is available here: https://salsa.debian.org/python-team/packages/python-datamodel-code-generator/
Thanks,
/Simon

typo: Fix 'Allow to' sentence.

---

datamodel_code_generator/parser/base.py
tests/data/expected/parser/openapi/openapi_parser_parse_duplicate_models_simplify/output.py
tests/data/openapi/duplicate_model_simplify.yaml
tests/parser/test_openapi.py
tox.ini
uv.lock

fix: Parser crashes when input contains duplicate schemas at root level

---

tox.ini

- Python 3.8 support has been dropped in https://github.com/koxudaxi/datamodel-code-generator/pull/2324
- Tox still has Python 3.8 among their envs

[Chore] Remove Python 3.8 from tox

---

src/datamodel_code_generator/arguments.py
tests/main/test_main_general.py

Fix #2333. Remove not none arg parse defaults.

---

src/datamodel_code_generator/__init__.py

Fixes: https://github.com/koxudaxi/datamodel-code-generator/issues/2362

fix: Pass encoding parameter to parser in init.generate()

---

src/datamodel_code_generator/parser/base.py

I'm afraid I don't know exactly what triggers this, but in my big openapi spec this gets triggered (with v0.30):
```
Traceback (most recent call last):
File "/home/gjc/.cache/uv/archive-v0/zrUKlPLuGJsfxDV0Mede0/lib/python3.12/site-packages/datamodel_code_generator/__main__.py", line 458, in main
generate(
File "/home/gjc/.cache/uv/archive-v0/zrUKlPLuGJsfxDV0Mede0/lib/python3.12/site-packages/datamodel_code_generator/__init__.py", line 492, in generate
results = parser.parse()
^^^^^^^^^^^^^^
File "/home/gjc/.cache/uv/archive-v0/zrUKlPLuGJsfxDV0Mede0/lib/python3.12/site-packages/datamodel_code_generator/parser/base.py", line 1311, in parse
self.__reuse_model(models, require_update_action_models)
File "/home/gjc/.cache/uv/archive-v0/zrUKlPLuGJsfxDV0Mede0/lib/python3.12/site-packages/datamodel …
```

fix: TypeError: '<' not supported between instances of 'str' and 'NoneType'

---

src/datamodel_code_generator/model/pydantic_v2/__init__.py
tests/data/expected/main/openapi/extra_template_data_config_pydantic_v2.py
tests/data/openapi/extra_data.json

Support setting `coerce_numbers_to_str` in the Pydantic `ConfigDict` via `extra_template_data`.
https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.coerce_numbers_to_str
There are other ConfigDict values that you might consider adding as well, but this one was the blocker for us.

Support `coerce_numbers_to_str` in `ConfigDict`

---

src/datamodel_code_generator/parser/jsonschema.py
tests/data/expected/parser/openapi/openapi_parser_parse_allof_required_fields/output.py
tests/data/expected/parser/openapi/openapi_parser_parse_anyof_required/output.py
tests/data/expected/parser/openapi/openapi_parser_parse_required_null/output.py
tests/data/openapi/allof_required_fields.yaml
tests/data/openapi/anyof_required.yaml
tests/data/openapi/required_null.yaml
tests/parser/test_openapi.py

The `required` field, when trying to get parsed as a `JsonSchemaObject` was only allowed to be of the type `list[str]`.
This PR adds a field validator which runs before, to pre-process `required` fields which are set to `null` or which have `anyOf`'s in them (like the OpenAPI schema's generated by [Elastic's Kibana API documentation](https://www.elastic.co/docs/api/doc/kibana/)).
Fixes #2297

Allow parsing non-string lists for required fields

---

tests/main/graphql/test_annotated.py
tests/main/graphql/test_main_graphql.py
tests/main/jsonschema/test_main_jsonschema.py
tests/main/openapi/test_main_openapi.py
tests/main/test_main_csv.py
tests/main/test_main_general.py
tests/main/test_main_json.py
tests/main/test_main_yaml.py
tests/parser/test_graphql.py
tests/test_main_kr.py

This PR wants to clean the tests replacing `TemporaryDirectory` with the `tmp_path` fixture as temporary directory path.
Also `tmpdir_factory` has been replaced with `tmp_path` since the factory was used as a single temporary path.
The advantages are:
- Use a standardized way to create temporary directories with PyTest (so the code is easier to understand)
- Fewer lines of code
- Remove one indentation block in most of the tests
Fixes #2462

Use Pytest `tmp_path` fixture instead of `TemporaryDirectory`

---

src/datamodel_code_generator/__init__.py
tests/test_infer_input_type.py

- If the content of a file can be parsed by `yaml`, it may be an OpenAPI, Jsonschema or JSON
- Otherwise, since CSV isn't standardized, we infer that it's a CSV file.
Extra:
- Improve error message when a file doesn't exist
Fixes https://github.com/koxudaxi/datamodel-code-generator/issues/2450

Automatically infer CSV file type
